[FILTER0]
LogAppName=AIS
ContextName=AIS
LogLevel=DLT_LOG_INFO
File=ais
FileSize=2000000
NOFiles=5

[FILTER1]
LogAppName=SYS
ContextName=JOUR
LogLevel=DLT_LOG_INFO
File=sys
FileSize=2000000
NOFiles=5


[FILTER99]
LogAppName=YVRS,YYURA,YPREVIEW,CMUP
ContextName=VRS,YURA,PREVIEW,CMUP
LogLevel=DLT_LOG_INFO
File=dvrs
FileSize=2000000
NOFiles=10
